version: "3"
services:
  netology-db:
    image: postgres:latest # Образ, который мы будем использовать
    container_name: netology-db # Имя, которым будет называться наш контейнер
    ports: # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера
      - 5432:5432
    volumes: # Папка, которую мы пробросим с докер сервера внутрь контейнера
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment: # Переменные среды
      POSTGRES_PASSWORD: 123 # Задаём пароль от пользователя postgres
      POSTGRES_DB: netology@mymail.me # БД которая сразу же будет создана
      PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка pgdata
    networks:
      isupoves-my-netology-hw:
        ipv4_address: 172.22.0.22
    restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускаться

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: netology@mymail.me
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "8080:80"
    networks:
      isupoves-my-netology-hw:
        ipv4_address: 172.22.0.33
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - netology-db
    container_name: isupoves-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.22'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "10052:10052"  #10051
    networks:
      isupoves-my-netology-hw:
        ipv4_address: 172.22.0.44
    restart: always

  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - netology-db
      - zabbix-server
    container_name: zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.22'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 123
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Europe/Moscow"
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      isupoves-my-netology-hw:
        ipv4_address: 172.22.0.55
    restart: always

networks:
  isupoves-my-netology-hw:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24
